#! /bin/sh
### BEGIN INIT INFO
# Provides:          sbbkp
# Default-Start:     
# Default-Stop:      0 1 2 3 4 5 6
# Short-Description: Starts sbbkp kbdd daemon.
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin

load_modules ()
{
	MODULES_MISSING=false

	for mod in $*
	do
		modprobe $mod 2> /dev/null || MODULES_MISSING=true
	done

	if [ "$MODULES_MISSING" = true ]; then
		echo "#####################################################"
		echo "## I couldn't load the required kernel modules     ##"
		echo "#####################################################"
	fi
}


test -f /usr/bin/kbdd || exit 0
test -f /usr/bin/rfcomm || exit 0

LOAD_MODULES=true
MODULES=uinput

BT_DEVICE=00:0A:3A:2F:0A:81
RF_CHANNEL=1
KB_TYPE=freedom

case "$1" in
  start)
    if [ "$LOAD_MODULES" = "true" ]; then
	load_modules $MODULES
    fi

    killall rfcomm kbdd 2> /dev/null

    echo -n "Starting sppkb daemon:"

    echo -n " rfcomm"
    RFCOMM_ARGS="--raw --encrypt --auth --secure \
	bind $RF_CHANNEL $BT_DEVICE"
    /usr/bin/rfcomm $RFCOMM_ARGS
    
    #while [[ ! -e /dev/rfcomm$RF_CHANNEL ]]
    #do
    #  sleep 1
    #done

    echo -n " kbdd"
    KBDD_ARGS="-p /dev/rfcomm$RF_CHANNEL -t $KB_TYPE"
    start-stop-daemon --start --quiet --background --nicelevel -1 --exec /usr/bin/kbdd -- $KBDD_ARGS

    echo .
    ;;

  stop)
    echo -n "Stopping sppkb daemon:"

    echo -n " rfcomm"
    #start-stop-daemon --stop --quiet --exec /usr/bin/rfcomm

    echo -n " kbdd"
    start-stop-daemon --stop --quiet --exec /usr/bin/kbdd

    echo .
    ;;

  restart)
    $0 stop
    $0 start
    ;;

  *)
    echo "Usage: /etc/init.d/bppkb {start|stop|restart}"
    exit 1
esac

exit 0
